# config.py

API_KEY = 'YOUR_ALPACA_API_KEY'
API_SECRET = 'YOUR_ALPACA_SECRET_KEY'
BASE_URL = 'https://paper-api.alpaca.markets'
SYMBOL = 'TSLA'

POSITION_SIZE_PCT = 0.10
TRAILING_STOP_PCT = 0.015
MAX_TRADES_PER_DAY = 10
DAILY_LOSS_LIMIT = 100  # in USD
TRADE_COOLDOWN_MINUTES = 5
